import type { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts/fonts";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "KENTA2525",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja" data-theme="lofi" className="bg-neutral">
      <body className={`${poppins.className} antialiased`}>
        <main className="m-2 bg-base-300 text-base-content rounded-4xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
