import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { mpr1c } from "@/app/fonts/fonts";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/_sections/_Footer/Footer";
import Spotlight from "@/app/_components/Spotlight";

export const metadata: Metadata = {
  title: "KENTA2525",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={'text-[14px]'}>
      <body
        className={`${mpr1c.className} antialiased bg-gradient-to-br from-teal-900 via-teal-950 via-55% to-black text-teal-50 leading-loose`}
      >
        <Spotlight>
          <Header />
          <main className={'px-4 min-h-dvh overflow-hidden'}>
            {children}
          </main>
          <Footer />
        </Spotlight>
      </body>
    </html>
  );
}
