import { Metadata } from 'next';
import './globals.css';
import { kleeOne } from '@/app/fonts/fonts';

export const metadata: Metadata = {
  title: 'KENTA2525',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // bg-gradient-to-br from-teal-900 via-teal-950 via-55% to-black
  return (
    <html
      lang='ja'
      className={'text-[14px]'}
    >
      <body className={`${kleeOne.className} antialiased`}>
        <main className={'px-4 min-h-dvh overflow-hidden'}>{children}</main>
      </body>
    </html>
  );
}
